version: '3.9'
services:
  mcp-server:
    build: .
    container_name: mcp_server
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      bash -c "python services/mcp_server/main.py"